Update compiler flags in conda-c-cpp.yml

diff --git a/.github/workflows/conda-c-cpp.yml b/.github/workflows/conda-c-cpp.yml
--- a/.github/workflows/conda-c-cpp.yml
+++ b/.github/workflows/conda-c-cpp.yml
@@ -38,14 +38,13 @@ jobs:
         #conda activate eclib-deps
         export CC=$CONDA_PREFIX/bin/clang
         export CXX=$CONDA_PREFIX/bin/clang++
-        export LDFLAGS="-L$CONDA_PREFIX/lib -Wl,-rpath,$CONDA_PREFIX/lib"
-        export CPPFLAGS="-I$CONDA_PREFIX/include"
         export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
         export DYLD_LIBRARY_PATH="$CONDA_PREFIX/lib:$DYLD_LIBRARY_PATH"  # Critical for macOS linking
         export MACOSX_DEPLOYMENT_TARGET=10.9  # Ensure compatibility
         export LDFLAGS="$LDFLAGS -L/usr/lib -L/usr/local/lib"
-        export CFLAGS="-fno-inline-asm -fPIC"
-        export CXXFLAGS="-fno-inline-asm -fPIC"
+        export CFLAGS="-I$CONDA_PREFIX/include -fno-inline-asm -fPIC"
+        export CXXFLAGS="-I$CONDA_PREFIX/include -fno-inline-asm -fPIC"
+        export LDFLAGS="-L$CONDA_PREFIX/lib -L/usr/lib -L/usr/local/lib" -Wl,-rpath,$CONDA_PREFIX/lib"
         echo "CC=$CC"
         echo "CXX=$CXX"
         echo "CONDA_PREFIX=$CONDA_PREFIX"
@@ -53,11 +52,12 @@ jobs:
         # Test if compiler works
         $CC --version
         echo 'int main() { return 0; }' > test.c
-        $CC $CPPFLAGS $LDFLAGS -o test test.c && echo "Compiler test PASSED" || { echo "Compiler test FAILED"; exit 1; }
+        $CC $CXXFLAGS $LDFLAGS -o test test.c && echo "Compiler test PASSED" || { echo "Compiler test FAILED"; exit 1; }
         rm -f test test.c
         $CXX --version
         ./autogen.sh
-        ./configure --with-boost="no" --with-flint --with-ntl=$CONDA_PREFIX --disable-allprogs --${{ matrix.mpfp }} CFLAGS="-fno-inline-asm"
+        ./configure --with-boost="no" --with-flint --with-ntl=$CONDA_PREFIX --disable-allprogs --${{ matrix.mpfp }}
+        cat config.log
     - name: make
       shell: bash -el {0}
       run: make
